# Generated by Django 4.2.13 on 2026-06-02 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('slots', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('merit', 'Merit-Based'), ('need', 'Need-Based'), ('sports', 'Sports'), ('arts', 'Arts & Culture'), ('stem', 'STEM'), ('general', 'General')], default='general', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scholarships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scholarships',
                'ordering': ['-created_at'],
            },
        ),
    ]
