# Generated by Django 4.2.13 on 2026-06-02 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_EDITED', 'User Edited'), ('USER_STATUS_CHANGED', 'User Status Changed'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('APPLICATION_REVIEWED', 'Application Reviewed'), ('APPLICATION_WITHDRAWN', 'Application Withdrawn'), ('SCHOLARSHIP_CREATED', 'Scholarship Created'), ('SCHOLARSHIP_UPDATED', 'Scholarship Updated'), ('SCHOLARSHIP_DELETED', 'Scholarship Deleted'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('API_REGISTER', 'API Register'), ('API_LOGIN', 'API Login'), ('API_LOGOUT', 'API Logout'), ('API_APPLICATION_SUBMITTED', 'API Application Submitted'), ('API_APPLICATION_REVIEWED', 'API Application Reviewed'), ('API_APPLICATION_WITHDRAWN', 'API Application Withdrawn'), ('API_SCHOLARSHIP_CREATED', 'API Scholarship Created'), ('API_SCHOLARSHIP_UPDATED', 'API Scholarship Updated'), ('API_SCHOLARSHIP_DELETED', 'API Scholarship Deleted')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
